# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cde1d932af4bd578c2d894a274fedfe1e2d001a04936899909e61da877b03ce7c3f0bd092fc1e582a1193ede22db5facc21fadcdde15692f48a6e076ab3f6299

test:
  secret_key_base: 59b12bc11f1d2c963b6334635cd19ca420a21f0632616276a673de44a4a279817d065fcc812c7b4f1102825851772a6809f627146497042f628f9166d0386f7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
